### ISSUE TITLE
start failure

### ISSUE THREAD

**Issue by veeramarni** [hemerajs/graphql-hemera#1]
I'm trying hemera for first and tried to start this project but it failed with below error. 

```
[2017-07-31T17:43:34.365Z] INFO (hemera-Veeras-MacBook-Pro.local-1ec3431fd1d345b0b60c2d178d8df6a3/95543 on Veeras-MacBook-Pro.local): hemera-joi PLUGIN - ADDED!
/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/graphql-hemera/node_modules/nats-hemera/lib/index.js:64
      throw config.error
      ^

ValidationError: "generators" is not allowed
    at Object.exports.process (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/graphql-hemera/node_modules/joi/lib/errors.js:181:19)
    at _validateWithOptions (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/graphql-hemera/node_modules/joi/lib/types/any/index.js:651:31)
    at root.validate (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/graphql-hemera/node_modules/joi/lib/index.js:121:23)
    at Hemera (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/graphql-hemera/node_modules/nats-hemera/lib/index.js:62:24)
    at Object.<anonymous> (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/graphql-hemera/src/index.js:25:16)
    at Module._compile (module.js:570:32)
    at loader (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/graphql-hemera/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/graphql-hemera/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by StarpTech** [comment]
Hi @veeramarni yes this issue results in an invalid configuration we removed this option in the last release as well as added config validation. You can easily remove the option `generators` in https://github.com/hemerajs/graphql-hemera/blob/master/src/index.js#L29 and it works. I will update it.

**Comment by StarpTech** [comment]
Changes pushed please try again.

**Comment by veeramarni** [comment]
Thanks, it works now.
